

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Documents" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "teamId" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "url" "text" NOT NULL,
    "role" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Documents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Interest" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "memberId" "text" NOT NULL,
    "terminId" "text" NOT NULL,
    "willParticipate" boolean DEFAULT false NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Interest" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Location" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "street" "text" NOT NULL,
    "number" "text" NOT NULL,
    "zip" "text" NOT NULL,
    "city" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Location" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Member" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "userProfileId" "text" NOT NULL,
    "teamId" "text" NOT NULL,
    "position" "text" NOT NULL,
    "role" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isBlocked" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Member" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "readedAt" timestamp with time zone,
    "senderId" "text" NOT NULL,
    "recipientId" "text" NOT NULL,
    "message" "text" NOT NULL
);


ALTER TABLE "public"."Messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Requests" (
    "id" bigint NOT NULL,
    "memberId" "text" NOT NULL,
    "teamId" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Requests" OWNER TO "postgres";


ALTER TABLE "public"."Requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Statistics" (
    "id" bigint NOT NULL,
    "memberId" "text" DEFAULT ''::"text" NOT NULL,
    "points" smallint DEFAULT '0'::smallint NOT NULL,
    "2ft" smallint DEFAULT '0'::smallint NOT NULL,
    "3ft" smallint DEFAULT '0'::smallint NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Statistics" OWNER TO "postgres";


ALTER TABLE "public"."Statistics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Statistics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Team" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "teamName" "text" NOT NULL,
    "createdBy" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "headcoach" "text" NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Team" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."TeamAdmin" (
    "id" bigint NOT NULL,
    "teamId" "text" NOT NULL,
    "role" "text" NOT NULL
);


ALTER TABLE "public"."TeamAdmin" OWNER TO "postgres";


ALTER TABLE "public"."TeamAdmin" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TeamAdmin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Termine" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "teamId" "uuid" NOT NULL,
    "type" "text" NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "locationId" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Termine" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."UserOnline" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "text" NOT NULL,
    "deviceToken" "text" NOT NULL,
    "firstName" "text" NOT NULL,
    "lastName" "text" NOT NULL
);


ALTER TABLE "public"."UserOnline" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."UserProfile" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "text" NOT NULL,
    "firstName" "text" NOT NULL,
    "lastName" "text" NOT NULL,
    "roleString" "text" DEFAULT '''Spieler''::text'::"text" NOT NULL,
    "birthday" "text" DEFAULT '''01.01.2025''::text'::"text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"(),
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "lastOnline" timestamp with time zone,
    "fcmToken" "text"
);


ALTER TABLE "public"."UserProfile" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Documents"
    ADD CONSTRAINT "Documents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Interest"
    ADD CONSTRAINT "Interest_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Location"
    ADD CONSTRAINT "Location_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Member"
    ADD CONSTRAINT "Member_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Messages"
    ADD CONSTRAINT "Messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Requests"
    ADD CONSTRAINT "Requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Statistics"
    ADD CONSTRAINT "Statistics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TeamAdmin"
    ADD CONSTRAINT "TeamAdmin_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Team"
    ADD CONSTRAINT "Team_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Team"
    ADD CONSTRAINT "Team_teamName_key" UNIQUE ("teamName");



ALTER TABLE ONLY "public"."Termine"
    ADD CONSTRAINT "Termine_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."UserOnline"
    ADD CONSTRAINT "UserOnline_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."UserProfile"
    ADD CONSTRAINT "UserProfile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."UserProfile"
    ADD CONSTRAINT "UserProfile_userId_key" UNIQUE ("userId");



ALTER TABLE "public"."Member" ENABLE ROW LEVEL SECURITY;


CREATE PUBLICATION "realtime_messages_publication_v2_34_0" WITH (publish = 'insert, update, delete, truncate');


ALTER PUBLICATION "realtime_messages_publication_v2_34_0" OWNER TO "supabase_admin";




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."Messages";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."UserOnline";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON TABLE "public"."Documents" TO "anon";
GRANT ALL ON TABLE "public"."Documents" TO "authenticated";
GRANT ALL ON TABLE "public"."Documents" TO "service_role";



GRANT ALL ON TABLE "public"."Interest" TO "anon";
GRANT ALL ON TABLE "public"."Interest" TO "authenticated";
GRANT ALL ON TABLE "public"."Interest" TO "service_role";



GRANT ALL ON TABLE "public"."Location" TO "anon";
GRANT ALL ON TABLE "public"."Location" TO "authenticated";
GRANT ALL ON TABLE "public"."Location" TO "service_role";



GRANT ALL ON TABLE "public"."Member" TO "anon";
GRANT ALL ON TABLE "public"."Member" TO "authenticated";
GRANT ALL ON TABLE "public"."Member" TO "service_role";



GRANT ALL ON TABLE "public"."Messages" TO "anon";
GRANT ALL ON TABLE "public"."Messages" TO "authenticated";
GRANT ALL ON TABLE "public"."Messages" TO "service_role";



GRANT ALL ON TABLE "public"."Requests" TO "anon";
GRANT ALL ON TABLE "public"."Requests" TO "authenticated";
GRANT ALL ON TABLE "public"."Requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Requests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Statistics" TO "anon";
GRANT ALL ON TABLE "public"."Statistics" TO "authenticated";
GRANT ALL ON TABLE "public"."Statistics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Statistics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Statistics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Statistics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Team" TO "anon";
GRANT ALL ON TABLE "public"."Team" TO "authenticated";
GRANT ALL ON TABLE "public"."Team" TO "service_role";



GRANT ALL ON TABLE "public"."TeamAdmin" TO "anon";
GRANT ALL ON TABLE "public"."TeamAdmin" TO "authenticated";
GRANT ALL ON TABLE "public"."TeamAdmin" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TeamAdmin_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TeamAdmin_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TeamAdmin_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Termine" TO "anon";
GRANT ALL ON TABLE "public"."Termine" TO "authenticated";
GRANT ALL ON TABLE "public"."Termine" TO "service_role";



GRANT ALL ON TABLE "public"."UserOnline" TO "anon";
GRANT ALL ON TABLE "public"."UserOnline" TO "authenticated";
GRANT ALL ON TABLE "public"."UserOnline" TO "service_role";



GRANT ALL ON TABLE "public"."UserProfile" TO "anon";
GRANT ALL ON TABLE "public"."UserProfile" TO "authenticated";
GRANT ALL ON TABLE "public"."UserProfile" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
